import Head from 'next/head'
import { useRouter } from 'next/router'

import PrimaryButton from '../components/PrimaryButton'

export default function Home() {
  const router = useRouter();
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center h-screen">
        <div className="flex flex-col">
          <h1 className="text-center text-5xl mb-5 font-bold">tasky</h1>
          <img className="w-screen mb-8" src="/assets/svgs/green-line.svg" alt="" />
          <PrimaryButton buttonMargin='0 auto 30px auto'>Sign In</PrimaryButton>
        </div>
      </main>
    </div>
  )
}
