import Head from 'next/head';
import { useRouter } from 'next/router';
import { signIn, signOut, useSession } from 'next-auth/react';
import styled from 'styled-components';

import PrimaryButton from '../components/PrimaryButton';

export default function Home() {
  const { data: session} = useSession();
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <StyledMain>
          <StyledH1>tasky</StyledH1>
          <StyledImage src="/assets/svgs/green-line.svg" alt="" />
          {!session && (
            <>
            <AuthStatus>Not Signed In</AuthStatus>
            <PrimaryButton clickFunc={signIn} buttonMargin='0 auto 30px auto'>Sign In</PrimaryButton>
            </>
          )}
          {session && (
            <>
              <AuthStatus>Signed in as {session.user.email}!</AuthStatus>
              <PrimaryButton clickFunc={() => router.push('/projects')} buttonMargin='0 auto 30px auto'>Projects</PrimaryButton>
              <PrimaryButton clickFunc={signOut} buttonMargin='0 auto 30px auto'>Sign Out</PrimaryButton>
            </>
          )}
      </StyledMain>
    </div>
  )
}

const StyledImage = styled.img`
  width: 100%;
  margin-bottom: 30px;
  @media screen and (min-width: 900px) {
    display: none;
  }
`;

const StyledH1 = styled.h1`
  text-align: center;
  font-size: 3.5rem;
  margin-bottom: 20px;
  font-weight: bold;
`;

const StyledMain = styled.main`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
  width: 100%;
`;

const AuthStatus = styled.p`
  margin: 0 auto 20px auto;
  font-size: 1.25rem;
  font-weight: 700;
`;