import Head from 'next/head';
import { useRouter } from 'next/router';
import { signIn, signOut, useSession } from 'next-auth/react';
import styled from 'styled-components';

import PrimaryButton from '../components/PrimaryButton';

export default function Home() {
  const { data: session, status } = useSession();
  const router = useRouter();
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex justify-center items-center h-screen'>
        <div className="flex flex-col">
          <h1 className="text-center text-5xl mb-5 font-bold">tasky</h1>
          <img className="w-screen mb-8" src="/assets/svgs/green-line.svg" alt="" />
          {!session && (
            <>
            <AuthStatus>Not Signed In</AuthStatus>
            <PrimaryButton clickFunc={signIn} buttonMargin='0 auto 30px auto'>Sign In</PrimaryButton>
            </>
          )}
          {session && (
            <>
              <AuthStatus>Signed in as {session.user.email}!</AuthStatus>
              <PrimaryButton clickFunc={() => router.push('/projects')} buttonMargin='0 auto 30px auto'>Projects</PrimaryButton>
              <PrimaryButton clickFunc={signOut} buttonMargin='0 auto 30px auto'>Sign Out</PrimaryButton>
            </>
          )}
        </div>
      </main>
    </div>
  )
}

const AuthStatus = styled.p`
  margin: 0 auto 20px auto;
  font-size: 1.25rem;
  font-weight: 700;
`;